### ISSUE TITLE
Please Opensource Recovery Tree for Lenovo A6000 Sir

### ISSUE THREAD

**Issue by dev-harsh1998** [SevenMaxs/android_kernel_asus_duma#1]
Sir please open source the recovery tree for lenovo a6000 and the kernel tree that you used to compile the recovery on ,it will help us in getting official cm13 support 
as we need a cyanogen compiled recovery to be compiled and pushed

regards
dev_harsh1998

**Comment by SevenMaxs** [comment]
Здравствуй.
Мне жаль, но я уже больше года назад прекратил поддержку этого устройства.
Но вы можете использовать последнюю мою сборку [Lenovo A6000 - Расширенное рекавери TWRP by SevenMaxs](url=http://lenovo-forums.ru/topic/12713-lenovo-a6000-расширенное-рекавери-twrp-by-sevenmaxs/)
Для самостоятельной сборки TWRP вы можете использовать [android_device_lenovo_a6000](url=https://github.com/amitwh/android_device_lenovo_a6000/tree/13.0)
и еще нужно добавить несколько флагов для TWRP:
# TWRP
```
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TARGET_RECOVERY_QCOM_RTC_FIX := true
BOARD_SUPPRESS_SECURE_ERASE := true
RECOVERY_SDCARD_ON_DATA := true
TW_DEFAULT_EXTERNAL_STORAGE := true
TW_BRIGHTNESS_PATH := /sys/class/leds/lcd-backlight/brightness
TW_INCLUDE_CRYPTO := true
TW_THEME := portrait_hdpi
```
Hi!
It is a pity to me, but I already as more than a year ago stopped support of this device.
But you can use the last my build [Lenovo A6000 - Расширенное рекавери TWRP by SevenMaxs](url=http://lenovo-forums.ru/topic/12713-lenovo-a6000-расширенное-рекавери-twrp-by-sevenmaxs/)
For self compiling TWRP, you can use [android_device_lenovo_a6000](url=https://github.com/amitwh/android_device_lenovo_a6000/tree/13.0)
And add TWRP flags:
# TWRP
```
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TARGET_RECOVERY_QCOM_RTC_FIX := true
BOARD_SUPPRESS_SECURE_ERASE := true
RECOVERY_SDCARD_ON_DATA := true
TW_DEFAULT_EXTERNAL_STORAGE := true
TW_BRIGHTNESS_PATH := /sys/class/leds/lcd-backlight/brightness
TW_INCLUDE_CRYPTO := true
TW_THEME := portrait_hdpi
```

Thx!
